paths:
  cluster: false
  measurement_cluster: "/n/home03/onikolaenko/NetKet/Haldane/measurement"
  data_cluster: "/n/home03/onikolaenko/NetKet/Haldane/data"
  measurement_local: "/Users/alexander/Documents/projects/NetKet/Haldane/measurement"
  data_local: "/Users/alexander/Documents/projects/NetKet/Haldane/data"

system:
  L: 4
  t1: 1.0              # nearest-neighbor hopping
  t2: 0.1              # next-nearest-neighbor hopping
  phi: 1.57079632679   # complex phase, e.g. pi/2
  m: 0.0               # sublattice staggering (Seminov mass)
  n_particles: 4     # total number of fermions, adjust as needed
  n_bands: 2
  seed: 0

model:
  embed_dim: 72
  n_heads: 12
  num_layers: 4
  patch_size: 1
  transl_invariant: false
  param_dtype: "float64"

sampling:
  n_samples: 8192
  n_chains: 8192
  d_max: 2
  n_discard_per_chain: 0
  chunk_size: 8192

optimizer:
  learning_rate: 0.03
  schedule: "cosine_decay"
  min_learning_rate: 0.003

vmc:
  diag_shift: 1.0e-4
  mode: "real"
  on_the_fly: true
  use_ntk: true
  n_iter: 500

logging:
  save_state_filename: "state_after_VMC.mpack"
  energy_filename: "energy_t2={t2:.3f}_phi={phi:.3f}_m={m:.3f}_L={L:d}_N={n_particles:d}_iter={n_iter:d}.txt"

wandb:
  use: false
  project: "haldane-netket"