_wandb:
    value:
        cli_version: 0.25.1
        e:
            b1ikdlchkuz3pi90gzp1y2nd5ml7cm04:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M2 Pro
                    pcpuCores: 6
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "10737418240"
                codePath: Kondo_model/kondo_run.py
                codePathLocal: kondo_run.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "368310837248"
                email: nikolajenko14@gmail.com
                executable: /usr/local/bin/python3
                git:
                    commit: 62d0ecb009eb0ccab5ddec2d9d9c0726da6c273f
                    remote: https://github.com/milkonavt/NetKet.git
                host: Alexanders-MacBook-Pro-2.local
                memory:
                    total: "17179869184"
                os: macOS-13.4-arm64-arm-64bit
                program: /Users/alexander/Documents/projects/NetKet/Kondo_model/kondo_run.py
                python: CPython 3.12.2
                root: /Users/alexander/Documents/projects/NetKet/Kondo_model
                startedAt: "2026-04-09T01:06:49.506867Z"
                writerId: b1ikdlchkuz3pi90gzp1y2nd5ml7cm04
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 12
                - 45
                - 105
            "2":
                - 12
                - 45
                - 105
            "3":
                - 13
                - 16
                - 41
            "4": 3.12.2
            "5": 0.25.1
            "12": 0.25.1
            "13": darwin-arm64
hamiltonian:
    value:
        J: 0
        Jk: 0
        U: 8
        t: 1
model:
    value:
        d_model: 8
        n_heads: 8
        num_layers: 1
        patch_size: 1
        transl_invariant: true
optimizer:
    value:
        diag_shift: 0.0001
        learning_rate: 0.03
        mode: real
        on_the_fly: true
        use_ntk: true
paths:
    value:
        cluster: false
        data_cluster: /n/home03/onikolaenko/NetKet/Kondo_model/data
        data_local: /Users/alexander/Documents/projects/NetKet/Kondo_model/data
        measurement_cluster: /n/home03/onikolaenko/NetKet/Kondo_model/measurement
        measurement_local: /Users/alexander/Documents/projects/NetKet/Kondo_model/measurement
sampler:
    value:
        chunk_size: 8192
        d_max: 2
        n_chains: 8192
        n_discard_per_chain: 0
        n_samples: 8192
        rule_probabilities:
            - 0.33333333
            - 0.33333333
            - 0.33333333
system:
    value:
        Lx: 4
        Ly: 4
        Ne: 2
        n_bands: 3
        pbc: true
training:
    value:
        init_seed: 1234
        n_iter: 500
        seed: 0
wandb:
    value:
        project: kondo-netket
        use_wandb: true
